let players = [
    {
        "id": "id50540979",
        "name": "Salah",
        "baseId": 209331,
        "rating": 91,
        "position": "RM",
        "altPositions": "RW",
        "color": "totw_gold",
        "clubId": 9,
        "leagueId": 13,
        "nationId": 111,
        "url": "https://i.imgur.com/2IO50TC.png",
        "totwNumber": 2,
        "packable": 0,
        "date": 4,
        "PAC": 91,
        "SHO": 90,
        "PAS": 83,
        "DRI": 91,
        "DEF": 47,
        "PHY": 77,
        "attack": 88,
        "control": 84,
        "defense": 51,
        "itemId": 162286
    },
    {
        "id": "id50520193",
        "name": "Lewandowski",
        "baseId": 188545,
        "rating": 91,
        "position": "ST",
        "altPositions": "",
        "color": "otw",
        "clubId": 241,
        "leagueId": 53,
        "nationId": 37,
        "url": "https://i.imgur.com/iQrd96D.png",
        "totwNumber": -1,
        "packable": 0,
        "date": 6,
        "PAC": 75,
        "SHO": 91,
        "PAS": 79,
        "DRI": 86,
        "DEF": 44,
        "PHY": 83,
        "attack": 89,
        "control": 79,
        "defense": 48,
        "itemId": 144924
    }, 
];
export { players };
