let players = [
    {
        "id": "id999094",
        "name": "Xabi Alonso",
        "baseId": 999094,
        "rating": 90,
        "position": "CDM",
        "altPositions": "",
        "color": "icon",
        "clubId": 112658,
        "leagueId": 2118,
        "nationId": 45,
        "url": "https://i.imgur.com/ncM7lVw.png",
        "totwNumber": -1,
        "packable": 0,
        "date": 0,
        "PAC": 70,
        "SHO": 80,
        "PAS": 88,
        "DRI": 81,
        "DEF": 85,
        "PHY": 82,
        "attack": 81,
        "control": 89,
        "defense": 88,
        "itemId": 258430
    },
    {
        "id": "id50524633",
        "name": "De Bruyne",
        "baseId": 192985,
        "rating": 92,
        "position": "CM",
        "altPositions": "CAM",
        "color": "totw_gold",
        "clubId": 10,
        "leagueId": 13,
        "nationId": 7,
        "url": "https://i.imgur.com/ZIP7cXu.png",
        "totwNumber": 1,
        "packable": 0,
        "date": 2,
        "PAC": 75,
        "SHO": 89,
        "PAS": 94,
        "DRI": 88,
        "DEF": 66,
        "PHY": 79,
        "attack": 87,
        "control": 89,
        "defense": 65,
        "itemId": 305182
    },
    {
        "id": "id999091",
        "name": "Jairzinho",
        "baseId": 999091,
        "rating": 92,
        "position": "RW",
        "altPositions": "",
        "color": "icon",
        "clubId": 112658,
        "leagueId": 2118,
        "nationId": 54,
        "url": "https://i.imgur.com/qMTEQ6f.png",
        "totwNumber": -1,
        "packable": 0,
        "date": 0,
        "PAC": 94,
        "SHO": 92,
        "PAS": 87,
        "DRI": 93,
        "DEF": 51,
        "PHY": 76,
        "attack": 93,
        "control": 91,
        "defense": 52,
        "itemId": 453230
    },
    {
        "id": "id999097",
        "name": "Müller",
        "baseId": 999097,
        "rating": 94,
        "position": "ST",
        "altPositions": "",
        "color": "icon",
        "clubId": 112658,
        "leagueId": 2118,
        "nationId": 21,
        "url": "https://i.imgur.com/GuoGL22.png",
        "totwNumber": -1,
        "packable": 0,
        "date": 0,
        "PAC": 88,
        "SHO": 94,
        "PAS": 77,
        "DRI": 88,
        "DEF": 43,
        "PHY": 76,
        "attack": 96,
        "control": 81,
        "defense": 44,
        "itemId": 552033
    },
    {
        "id": "id50508651",
        "name": "Modric",
        "baseId": 177003,
        "rating": 89,
        "position": "CM",
        "altPositions": "",
        "color": "totw_gold",
        "clubId": 243,
        "leagueId": 53,
        "nationId": 10,
        "url": "https://i.imgur.com/0ohqUBB.png",
        "totwNumber": 2,
        "packable": 0,
        "date": 4,
        "PAC": 75,
        "SHO": 78,
        "PAS": 90,
        "DRI": 89,
        "DEF": 73,
        "PHY": 67,
        "attack": 83,
        "control": 88,
        "defense": 70,
        "itemId": 329448
    },
    {
        "id": "id50540979",
        "name": "Salah",
        "baseId": 209331,
        "rating": 91,
        "position": "RM",
        "altPositions": "RW",
        "color": "totw_gold",
        "clubId": 9,
        "leagueId": 13,
        "nationId": 111,
        "url": "https://i.imgur.com/2IO50TC.png",
        "totwNumber": 2,
        "packable": 0,
        "date": 4,
        "PAC": 91,
        "SHO": 90,
        "PAS": 83,
        "DRI": 91,
        "DEF": 47,
        "PHY": 77,
        "attack": 88,
        "control": 84,
        "defense": 51,
        "itemId": 162286
    },
    {
        "id": "id50520193",
        "name": "Lewandowski",
        "baseId": 188545,
        "rating": 91,
        "position": "ST",
        "altPositions": "",
        "color": "otw",
        "clubId": 241,
        "leagueId": 53,
        "nationId": 37,
        "url": "https://i.imgur.com/iQrd96D.png",
        "totwNumber": -1,
        "packable": 0,
        "date": 6,
        "PAC": 75,
        "SHO": 91,
        "PAS": 79,
        "DRI": 86,
        "DEF": 44,
        "PHY": 83,
        "attack": 89,
        "control": 79,
        "defense": 48,
        "itemId": 144924
    }, 
];
export { players };
